config/routes.rb
Rails.application.routes.draw do
  resources :stations
  resources :houses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/house.rb
class House < ApplicationRecord
	has_many :stations
	accepts_nested_attributes_for :stations, limit: 2, allow_destroy: true
end

app/models/station.rb
class Station < ApplicationRecord
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]

  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
    2.times { @house.stations.build }
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to @house, notice: 'House was successfully created.' }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html { redirect_to houses_url, notice: 'House was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_params
      params.require(:house).permit(:name, :rent, :address, :age, :note, stations_attributes: [:route_name, :name, :duration])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:route_name, :name, :duration)
    end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/houses/_form.html.erb
<%= form_for(house) do |f| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% house.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.text_field :rent %><%= t('number.currency.format.unit') %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %><%= t('datetime.prompts.year') %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_area :note %>
  </div>

  <hr/>

  <%= f.fields_for(:stations) do |s| %>
    <h2><%= Station.model_name.human %><%= s.index + 1 %></h2>

    <div class="field">
      <%= s.label :route_name %>
      <%= s.text_field :route_name %>
    </div>

    <div class="field">
      <%= s.label :name %>
      <%= s.text_field :name %>
    </div>

    <div class="field">
      <%= s.label :duration %>
      <%= s.text_field :duration %><%= t('datetime.prompts.minute') %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1><%= House.model_name.human %><%= t '.title' %></h1>

<%= render 'form', house: @house %>

<%= link_to t('helpers.show'), @house %> |
<%= link_to t('helpers.back'), houses_path %>

app/views/houses/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= House.model_name.human %><%= t '.title' %></h1>

<table>
  <thead>
    <tr>
      <th><%= House.human_attribute_name('name') %></th>
      <th><%= House.human_attribute_name('rent') %></th>
      <th><%= House.human_attribute_name('address') %></th>
      <th><%= House.human_attribute_name('age') %></th>
      <th><%= House.human_attribute_name('note') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.name %></td>
        <td><%= number_with_delimiter house.rent %><%= t('number.currency.format.unit') %></td>
        <td><%= house.address %></td>
        <td><%= house.age %><%= t('datetime.prompts.year') %></td>
        <td><%= house.note %></td>
        <td><%= link_to t('helpers.show'), house %></td>
        <td><%= link_to t('helpers.edit'), edit_house_path(house) %></td>
        <td><%= link_to t('helpers.destroy'), house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to(new_house_path) do %>
  <%= House.model_name.human %><%= t('helpers.link.create') %>
<% end %>

app/views/houses/new.html.erb
<h1><%= House.model_name.human %><%= t '.title' %></h1>

<%= render 'form', house: @house %>

<%= link_to t('helpers.back'), houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= House.human_attribute_name('name') %>: </strong>
  <%= @house.name %>
</p>

<p>
  <strong><%= House.human_attribute_name('rent') %>: </strong>
  <%= number_with_delimiter @house.rent %><%= t('number.currency.format.unit') %>
</p>

<p>
  <strong><%= House.human_attribute_name('address') %>: </strong>
  <%= @house.address %>
</p>

<p>
  <strong><%= House.human_attribute_name('age') %></strong>
  <%= @house.age %><%= t('datetime.prompts.year') %>
</p>

<p>
  <strong><%= House.human_attribute_name('note') %></strong>
  <%= @house.note %>
</p>

<hr/>

<% @house.stations.each_with_index do |station, i| %>
  <h2><%= Station.model_name.human %><%= i + 1 %></h2>

  <p>
    <strong><%= Station.human_attribute_name('route_name') %></strong>
    <%= station.route_name %>
  </p>

  <p>
    <strong><%= Station.human_attribute_name('name') %></strong>
    <%= station.name %>
  </p>

  <p>
    <strong><%= Station.human_attribute_name('duration') %></strong>
    <%= station.duration %><%= t('datetime.prompts.minute') %>
  </p>
<% end %>

<%= link_to t('helpers.edit'), edit_house_path(@house) %> |
<%= link_to t('helpers.back'), houses_path %>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :route_name %>
    <%= f.text_field :route_name %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Route name</th>
      <th>Name</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.route_name %></td>
        <td><%= station.name %></td>
        <td><%= station.duration %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route name:</strong>
  <%= @station.route_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @station.duration %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>